# PHP-FPM role tasks
---

- name: Add PHP repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Update apt repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install PHP 8.2 and PHP-FPM 8.2
  apt:
    name:
      - php8.2
      - php8.2-fpm
      - php-pdo-mysql
      - php-mysql
    state: present
  notify:
    - Restart php8.2-fpm

- name: Copy php app files
  copy:
    src: ../services/php-service/
    dest: /apps/php-service
    
- name: Add php-service Nginx config
  template:
    src: ../services/php-service/php-service
    dest: /etc/nginx/sites-available/php-service

- name: Enable Nginx config
  file:
    src: /etc/nginx/sites-available/php-service
    dest: /etc/nginx/sites-enabled/php-service
    state: link
  notify:
    - Restart Nginx
