# PHP-FPM role tasks
---

- name: Add PHP repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Update apt repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install PHP 8.2 and PHP-FPM 8.2
  apt:
    name:
      - php8.2
      - php8.2-fpm
      - php8.2-mysql
    state: present
    
- name: Create phpfpm user
  user:
    name: "phpfpm"
    state: present
    
- name: Remove files in app directory
  ansible.builtin.command:
    cmd: "rm -rf /apps/php-service/*"

- name: Copy php app files
  copy:
    src: ../services/php-service/index.php
    dest: /apps/php-service/index.php
    
- name: UFW - Allow 9000 port
  community.general.ufw:
    rule: allow
    port: '9000'
    proto: tcp
    
- name: Add php-service PHP-FPM config
  copy:
    src: ../services/php-service/php-service-pool.conf
    dest: /etc/php/8.2/fpm/pool.d/php-service-pool.conf

- name: Add php-service Nginx config
  copy:
    src: ../services/php-service/php-service
    dest: /etc/nginx/sites-available/php-service 

- name: Enable Nginx config
  file:
    src: /etc/nginx/sites-available/php-service
    dest: /etc/nginx/sites-enabled/php-service
    state: link
  notify:
    - Restart php8.2-fpm
    - Restart Nginx
