# PHP-FPM role tasks
---

- name: Add PHP repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Update apt repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: "Install PHP {{ php_version }} and PHP-FPM {{ php_version }}"
  apt:
    name:
      - "php{{ php_version }}"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-mysql"
    state: present
    
- name: Create phpfpm user
  user:
    name: "phpfpm"
    state: present
    
- name: Create php app directory
  file:
    path: {{ php_service_app_directory_path }}
    state: directory

- name: Remove files in app directory
  ansible.builtin.command:
    cmd: "rm -rf {{ php_service_app_directory_path }}/*"

- name: Copy php app files
  copy:
    src: {{ php_service_app_source_path }}
    dest: {{ php_service_app_destination_path }}
        
- name: Add php-service PHP-FPM config
  copy:
    src: {{ php_fpm_source_config_path }}
    dest: {{ php_fpm_destination_config_path }}
  notify:
    - "Restart php{{ php_version }}-fpm"

#- name: Add php-service Nginx config
#  copy:
#    src: ../services/php-service/php-service.nginx
#    dest: /etc/nginx/sites-available/php-service.nginx

#- name: Enable Nginx config
#  file:
#    src: /etc/nginx/sites-available/php-service.nginx
#    dest: /etc/nginx/sites-enabled/php-service.nginx
#    state: link
#  notify:
#    - Restart php8.2-fpm
#    - Restart Nginx

#- name: UFW - Allow 9000 port
#  community.general.ufw:
#    rule: allow
#    port: '9000'
#    proto: tcp