# Apply default server settings
---
- name: Install required packages
  apt:
    pkg:
      - curl
      - vim
      - git
      - ufw
      - htop
    state: latest
    update_cache: true
    
- name: Stop Apache
  systemd:
    name: apache2
    state: stopped

- name: UFW - Allow SSH connections
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: UFW - Enable and deny by default
  community.general.ufw:
    state: enabled
    default: deny