# HAProxy role tasks
---

- name: Update apt repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  
- name: Install HAProxy
  apt:
    name: haproxy
    state: present

- name: Copy HAProxy configuration
  copy:
    src: ../services/haproxy/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg 

- name: Copy ssl certificate
  copy:
    src: ../services/haproxy/prod-02.ip03.ru.pem
    dest: /etc/haproxy/prod-02.ip03.ru.pem

- name: Check HAProxy configuration
  command: haproxy -c -f /etc/haproxy/haproxy.cfg
  register: result
  ignore_errors: true
  notify:
    - Restart HAProxy

- name: Fail if HAProxy config is invalid
  fail:
    msg: "HAProxy configuration is invalid"
  when: result.rc != 0

- name: UFW - Allow Nginx Full connections
  community.general.ufw:
    rule: allow
    name: Nginx Full
