# MySql role tasks

- name: Update apt repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Installing MySql and dependencies
  apt:
    name:
      - mysql-server
      - mysql-client
      - libmysqlclient-dev
      - python3-mysqldb
      - php-mysql
    state: present
 
- name: Start and enable mysql service
  service:
    name: mysql
    state: started
    enabled: yes
    
- name: Creating mysql user
  mysql_user:
    name: "{{db_user}}"
    password: "{{db_pass}}"
    priv: '*.*:ALL'
    host: '%'
    state: present
    
- name: Creating database
  mysql_db:
    name: "{{db_name}}"
    state: present
    
- name: Enable only 127.0.0.1 login
  lineinfile:
     path: /etc/mysql/mysql.conf.d/mysqld.cnf
     regexp: '^bind-address'
     line: 'bind-address = 127.0.0.1'
     backup: yes
  notify:
     - Restart mysql
