# NodeJS role tasks
---

- name: Update apt repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  
- name: Install GPG
  apt:
    name: gnupg
    state: present

- name: Install the gpg key for nodejs LTS
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key"
    state: present

- name: Install the nodejs LTS repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x nodistro main"
    state: present
    update_cache: yes

- name: Install NodeJS
  tags: nodesjs, install
  apt:
    name: nodejs
    state: latest

- name: Create node user
  user:
    name: "node"
    state: present

- name: Create nodejs app directory
  file:
    path: "{{ nodejs_service_app_directory_path }}"
    state: directory

- name: Remove files in app directory
  ansible.builtin.command:
    cmd: "rm -rf {{ nodejs_service_app_directory_path }}/*"
    
- name: Copy node app files
  copy:
    src: "{{ nodejs_service_app_source_path }}"
    dest: "{{ nodejs_service_app_destination_path }}"

- name: Create systemd service file
  template:
    src: "{{ nodejs_service_systemd_source_path }}"
    dest: "{{ nodejs_service_systemd_destination_path }}"

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Start Nodejs service
  systemd:
    name: nodejs-service
    state: started
    enabled: yes
    
#- name: Add nodejs-service Nginx config
#  template:
#    src: ../services/nodejs-service/nodejs-service.nginx
#    dest: /etc/nginx/sites-available/nodejs-service.nginx

#- name: Enable Nginx config
#  file:
#    src: /etc/nginx/sites-available/nodejs-service.nginx
#    dest: /etc/nginx/sites-enabled/nodejs-service.nginx
#    state: link
#  notify:
#    - Restart Nginx

#- name: UFW - Allow 8000 port
#  community.general.ufw:
#    rule: allow
#    port: '8000'
#    proto: tcp