# Nginx role tasks
---

- name: Update apt repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Installing Nginx
  apt:
    name: nginx
    state: present

- name: Remove default nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Copy Nginx configuration file
  copy:
    src: ../services/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - Restart Nginx

