# Nginx role tasks
---

- name: Update apt repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Installing Nginx
  apt:
    name: nginx
    state: present

- name: Remove default nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Add apps Nginx config
  copy:
    src: "{{ nginx_source_config_path }}"
    dest: "{{ nginx_apps_config_path }}"

- name: Enable Nginx config
  file:
    src: "{{ nginx_apps_config_path }}"
    dest: "{{ nginx_destination_config_path }}"
    state: link
  notify:
    - Restart Nginx

- name: Create nginx sll directory
  file:
    path: "{{ nginx_ssl_directory_path }}"
    state: directory

- name: Add ssl_certificate
  copy:
    src: "{{ ssl_certificate_source }}"
    dest: "{{ ssl_certificate_destination }}"

- name: Add ssl_certificate_key
  copy:
    src: "{{ ssl_certificate_key_source }}"
    dest: "{{ ssl_certificate_key_destination }}"
