# Nginx role tasks
---

- name: Update apt repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Installing Nginx
  apt:
    name: nginx
    state: present

- name: Remove default nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - Restart Nginx

- name: Create nginx sll directory
  file:
    path: /etc/nginx/ssl
    state: directory

- name: Add ssl_certificate
  copy:
    src: ../services/nginx/prod-02.ip03.ru_fullchain.pem
    dest: /etc/nginx/ssl/prod-02.ip03.ru_fullchain.pem

- name: Add ssl_certificate_key
  copy:
    src: ../services/nginx/prod-02.ip03.ru_privkey.pem
    dest: /etc/nginx/ssl/prod-02.ip03.ru_privkey.pem
