- hosts: all
  become: true

  tasks:
    - name: Installing Nginx
      apt:
        name: nginx
        state: present

    - name: Remove default nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Copy Nginx configuration file
      copy:
        src: ./services/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - Restart Nginx

  handlers:
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
