# First server setup
---
- hosts: all
  become: true

  tasks:        
    - name: Create ansible_user user with sudo privileges
      user:
        name: "{{ ansible_username }}"
        state: present
        groups: sudo
        append: true
        create_home: true
        
    - name: Set passwordless sudo for ansible_user
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^{{ ansible_username }} ALL='
        line: "{{ ansible_username }} ALL=(ALL) NOPASSWD: ALL"
        validate: '/usr/sbin/visudo -cf %s'

    - name: Set authorized key for remote user
      ansible.posix.authorized_key:
        user: "{{ ansible_username }}"
        state: present
        key: "{{ ansible_public_key }}"

    - name: Disable password authentication for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'

    - name: Disable tunneled clear-text passwords
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^PasswordAuthentication yes'
        line: 'PasswordAuthentication no'

    - name: Install required packages
      apt:
        pkg:
          - curl
          - vim
          - git
          - ufw
          - htop
        state: latest
        update_cache: true

    - name: UFW - Allow SSH connections
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: UFW - Enable and deny by default
      community.general.ufw:
        state: enabled
        default: deny
