name: Ansible Lint

on:
  push:
    paths:
      - 'ansible/roles/**'
  pull_request:
    paths:
      - 'ansible/roles/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
    - name: Run ansible lint test
      run: echo "Running ansible lint test..."

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install ansible-lint
      run: pip install ansible-lint

    - name: Run ansible-lint
      run: ansible-lint ansible/ --skip-list "syntax-check"
