name: Ansible_lint

on:
  push:
    paths:
      - 'ansible/roles/**'
  pull_request:
    paths:
      - 'ansible/roles/**'
  workflow_dispatch:
  
jobs:
  lint-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
    
      - name: Setup Lint
        uses: bec-galaxy/setup-lint@{Version}
    
      - name: Run Lint tests
        run: ansible-lint
